/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import InterfacesVistas.IMaterial;
import Presentador.PMaterial;
import javax.swing.JOptionPane;

/**
 *
 * @author sroma
 */
public class VMaterial extends javax.swing.JFrame implements IMaterial{

    /**
     * Creates new form VMaterial
     */
    public VMaterial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        unidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        grupo = new javax.swing.JTextField();
        bnuevo = new javax.swing.JButton();
        bguardar = new javax.swing.JButton();
        beditar = new javax.swing.JButton();
        bcancelar = new javax.swing.JButton();
        beliminar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        buscarmaterial = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablamaterial = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Nombre:");
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        nombre.setBorder(null);
        nombre.setCaretColor(new java.awt.Color(102, 102, 102));
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 137, 20));

        unidad.setBorder(null);
        unidad.setCaretColor(new java.awt.Color(102, 102, 102));
        jPanel1.add(unidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 148, 137, 20));

        jLabel2.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Unidad:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Grupo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 20));

        grupo.setBorder(null);
        grupo.setCaretColor(new java.awt.Color(102, 102, 102));
        grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupoActionPerformed(evt);
            }
        });
        jPanel1.add(grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 202, 137, 20));

        bnuevo.setText("Nuevo");
        bnuevo.setBorder(null);
        bnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnuevoActionPerformed(evt);
            }
        });
        jPanel1.add(bnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 60, 30));

        bguardar.setText("Guardar");
        jPanel1.add(bguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, 30));

        beditar.setText("Editar");
        beditar.setBorder(null);
        beditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditarActionPerformed(evt);
            }
        });
        jPanel1.add(beditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 60, 30));

        bcancelar.setText("Cancelar");
        bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelarActionPerformed(evt);
            }
        });
        jPanel1.add(bcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, 30));

        beliminar.setText("Eliminar");
        beliminar.setBorder(null);
        beliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliminarActionPerformed(evt);
            }
        });
        jPanel1.add(beliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 60, 40));

        buscar.setText("Buscar");
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));
        jPanel1.add(buscarmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 129, -1));

        tablamaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Unidad", "Grupo"
            }
        ));
        jScrollPane2.setViewportView(tablamaterial);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 285, 587, 132));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded

    }//GEN-LAST:event_jLabel1AncestorAdded

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grupoActionPerformed

    private void bnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnuevoActionPerformed

    }//GEN-LAST:event_bnuevoActionPerformed

    private void beditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditarActionPerformed

    }//GEN-LAST:event_beditarActionPerformed

    private void bcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcancelarActionPerformed

    private void beliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliminarActionPerformed

    }//GEN-LAST:event_beliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    @Override
    public void setPresentador(PMaterial m) {
        bnuevo.addActionListener(m);
        bguardar.addActionListener(m);
        bcancelar.addActionListener(m);
        beditar.addActionListener(m);
        beliminar.addActionListener(m);
        buscar.addActionListener(m);
    }

    @Override
    public void iniciar() {
        bguardar.setEnabled(false);
        bcancelar.setEnabled(false);
        nombre.setEnabled(false);
        unidad.setEnabled(false);
        grupo.setEnabled(false);
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    @Override
    public String getnombre() {
        return nombre.getText();
    }

    @Override
    public String getunidad() {
        return unidad.getText();
    }

    @Override
    public String getgrupo() {
        return grupo.getText();
    }

    @Override
    public String getBusqueda() {
        return buscarmaterial.getText();
    }

    @Override
    public int getItem() {
        if(tablamaterial.getSelectedRow()!=-1){
            return Integer.parseInt(String.valueOf(tablamaterial.getValueAt(tablamaterial.getSelectedRow(), 0)));
        } else{
            return -1;
        }
    }

    @Override
    public void setSalida(String[][] lista) {
        tablamaterial.setModel(new javax.swing.table.DefaultTableModel(lista,new String [] {"Id", "Nombre","Unidad","Grupo"}));
    }

    @Override
    public void mostrarMensaje(String output) {
        JOptionPane.showMessageDialog(null, output);
    }

    @Override
    public void habilitar() {
        beliminar.setEnabled(false);
        bnuevo.setEnabled(false);
        bguardar.setEnabled(true);
        bcancelar.setEnabled(true);
        beditar.setEnabled(false);
        nombre.setEnabled(true);
        unidad.setEnabled(true);
        grupo.setEnabled(true);
        
    }

    @Override
    public void restaurar() {
        beliminar.setEnabled(true);
        bnuevo.setEnabled(true);
        bguardar.setEnabled(false);
        bcancelar.setEnabled(false);
        beditar.setEnabled(true);        
        nombre.setEnabled(false);
        unidad.setEnabled(false);
        grupo.setEnabled(false);
        
        limpiarCampos();
    }
    
     private void limpiarCampos(){
        nombre.setText("");
        unidad.setText("");
        grupo.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcancelar;
    public javax.swing.JButton beditar;
    public javax.swing.JButton beliminar;
    private javax.swing.JButton bguardar;
    public javax.swing.JButton bnuevo;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField buscarmaterial;
    public javax.swing.JTextField grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public javax.swing.JTextField nombre;
    private javax.swing.JTable tablamaterial;
    public javax.swing.JTextField unidad;
    // End of variables declaration//GEN-END:variables
}
